[2024-11-27T23:19:41.035+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T23:19:41.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet manual__2024-11-27T23:12:33.689041+00:00 [queued]>
[2024-11-27T23:19:41.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet manual__2024-11-27T23:12:33.689041+00:00 [queued]>
[2024-11-27T23:19:41.076+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-11-27T23:19:41.091+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_kafka_to_parquet> on 2024-11-27 23:12:33.689041+00:00
[2024-11-27T23:19:41.098+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4499) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T23:19:41.097+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'run_spark_kafka_to_parquet', 'manual__2024-11-27T23:12:33.689041+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp8o1gu0u2']
[2024-11-27T23:19:41.099+0000] {standard_task_runner.py:64} INFO - Started process 4500 to run task
[2024-11-27T23:19:41.099+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask run_spark_kafka_to_parquet
[2024-11-27T23:19:41.138+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet manual__2024-11-27T23:12:33.689041+00:00 [running]> on host cc9ad6cea7ef
[2024-11-27T23:19:41.206+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='run_spark_kafka_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T23:12:33.689041+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T23:12:33.689041+00:00'
[2024-11-27T23:19:41.207+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T23:19:41.217+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-27T23:19:41.218+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit ./kafka_to_parquet.py']
[2024-11-27T23:19:41.225+0000] {subprocess.py:86} INFO - Output:
[2024-11-27T23:19:41.226+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2024-11-27T23:19:41.227+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-27T23:19:41.227+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T23:19:41.235+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-27T23:19:41.239+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=run_spark_kafka_to_parquet, run_id=manual__2024-11-27T23:12:33.689041+00:00, execution_date=20241127T231233, start_date=20241127T231941, end_date=20241127T231941
[2024-11-27T23:19:41.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task run_spark_kafka_to_parquet (Bash command failed. The command returned a non-zero exit code 127.; 4500)
[2024-11-27T23:19:41.273+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-27T23:19:41.286+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T23:19:41.288+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
