<<<<<<< HEAD
[2024-11-30T20:35:46.759+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T20:35:46.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T19:00:00+00:00 [queued]>
[2024-11-30T20:35:46.846+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T19:00:00+00:00 [queued]>
[2024-11-30T20:35:46.856+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-30T20:35:46.916+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_openweathermap_data> on 2024-11-30 19:00:00+00:00
[2024-11-30T20:35:46.931+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=17336) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T20:35:46.933+0000] {standard_task_runner.py:64} INFO - Started process 17339 to run task
[2024-11-30T20:35:46.931+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'store_openweathermap_data', 'scheduled__2024-11-30T19:00:00+00:00', '--job-id', '454', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpz9vam7ke']
[2024-11-30T20:35:46.935+0000] {standard_task_runner.py:91} INFO - Job 454: Subtask store_openweathermap_data
[2024-11-30T20:35:47.037+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T19:00:00+00:00 [running]> on host 0741a2a1545f
[2024-11-30T20:35:47.297+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='store_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-30T19:00:00+00:00'
[2024-11-30T20:35:47.302+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T20:35:47.337+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T20:35:47.345+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 147, in store_openweathermap_data
    read_from_kafka_and_store(KAFKA_TOPIC_OPENWEATHER, "openweathermap_data.parquet")
  File "/opt/airflow/dags/kafka_stream.py", line 142, in read_from_kafka_and_store
    logging.error(f"Error reading from Kafka topic {topic_name}: {e}")
                                                                  ^
NameError: name 'e' is not defined
[2024-11-30T20:35:47.370+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=store_openweathermap_data, run_id=scheduled__2024-11-30T19:00:00+00:00, execution_date=20241130T190000, start_date=20241130T203546, end_date=20241130T203547
[2024-11-30T20:35:47.426+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 454 for task store_openweathermap_data (name 'e' is not defined; 17339)
[2024-11-30T20:35:47.470+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-30T20:35:47.497+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T20:35:47.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
=======
[2024-11-30T20:07:35.281+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T20:07:35.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T19:00:00+00:00 [queued]>
[2024-11-30T20:07:35.672+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T19:00:00+00:00 [queued]>
[2024-11-30T20:07:35.733+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-30T20:07:35.895+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_openweathermap_data> on 2024-11-30 19:00:00+00:00
[2024-11-30T20:07:36.023+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'store_openweathermap_data', 'scheduled__2024-11-30T19:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmppocwsyj2']
[2024-11-30T20:07:36.041+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=15803) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T20:07:36.048+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask store_openweathermap_data
[2024-11-30T20:07:36.105+0000] {standard_task_runner.py:64} INFO - Started process 15814 to run task
[2024-11-30T20:07:36.745+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T19:00:00+00:00 [running]> on host 8885fe629c2f
[2024-11-30T20:07:37.906+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='store_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-30T19:00:00+00:00'
[2024-11-30T20:07:37.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T20:07:38.218+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: connecting to broker:9092 [('172.23.0.9', 9092) IPv4]
[2024-11-30T20:07:38.222+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-11-30T20:07:38.229+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: Connection complete.
[2024-11-30T20:07:38.412+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-11-30T20:07:38.427+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-11-30T20:07:38.445+0000] {consumer.py:122} WARNING - group_id is None: disabling auto-commit.
[2024-11-30T20:07:38.462+0000] {subscription_state.py:167} INFO - Updating subscribed topics to: ('openweathermap_raw',)
[2024-11-30T20:07:38.508+0000] {subscription_state.py:253} INFO - Updated partition assignment: [('openweathermap_raw', 0)]
[2024-11-30T20:07:38.524+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: connecting to broker:9092 [('172.23.0.9', 9092) IPv4]
[2024-11-30T20:07:38.554+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: Connection complete.
[2024-11-30T20:07:38.602+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.23.0.9', 9092)]>: Closing connection. 
[2024-11-30T20:07:39.245+0000] {logging_mixin.py:188} INFO - Consumed 100 records from topic openweathermap_raw
[2024-11-30T20:07:39.768+0000] {logging_mixin.py:188} INFO - Data from openweathermap_raw stored in /opt/***/data/parquet_files/openweathermap_data.parquet
[2024-11-30T20:07:39.769+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-30T20:07:39.770+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T20:07:39.811+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_kafka_dag, task_id=store_openweathermap_data, run_id=scheduled__2024-11-30T19:00:00+00:00, execution_date=20241130T190000, start_date=20241130T200735, end_date=20241130T200739
[2024-11-30T20:07:39.969+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-30T20:07:40.077+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T20:07:40.120+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
>>>>>>> 604b8b813e1d85ccda3063889c3dd1126b7c5791
