[2024-12-03T15:25:05.643+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T15:25:05.716+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.spark_submit manual__2024-12-03T15:19:29.807027+00:00 [queued]>
[2024-12-03T15:25:05.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.spark_submit manual__2024-12-03T15:19:29.807027+00:00 [queued]>
[2024-12-03T15:25:05.735+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-12-03T15:25:05.790+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_submit> on 2024-12-03 15:19:29.807027+00:00
[2024-12-03T15:25:05.799+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'spark_submit', 'manual__2024-12-03T15:19:29.807027+00:00', '--job-id', '767', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpv_wd81ao']
[2024-12-03T15:25:05.806+0000] {standard_task_runner.py:91} INFO - Job 767: Subtask spark_submit
[2024-12-03T15:25:05.824+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=906) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T15:25:05.829+0000] {standard_task_runner.py:64} INFO - Started process 908 to run task
[2024-12-03T15:25:05.923+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.spark_submit manual__2024-12-03T15:19:29.807027+00:00 [running]> on host 0f9edd113eb4
[2024-12-03T15:25:06.011+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T15:19:29.807027+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T15:19:29.807027+00:00'
[2024-12-03T15:25:06.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T15:25:06.030+0000] {spark_submit.py:304} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-12-03T15:25:06.031+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --py-files /dependencies.zip --packages com.datastax.spark:spark-cassandra-connector_2.12:3.5.1 --name docker_spark_task /spark_stream.py
[2024-12-03T15:25:06.103+0000] {spark_submit.py:634} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-12-03T15:25:06.104+0000] {spark_submit.py:634} INFO - JAVA_HOME is not set
[2024-12-03T15:25:06.104+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T15:25:06.111+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --py-files /dependencies.zip --packages com.datastax.spark:spark-cassandra-connector_2.12:3.5.1 --name docker_spark_task /spark_stream.py. Error code is: 1.
[2024-12-03T15:25:06.114+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=spark_submit, run_id=manual__2024-12-03T15:19:29.807027+00:00, execution_date=20241203T151929, start_date=20241203T152505, end_date=20241203T152506
[2024-12-03T15:25:06.124+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 767 for task spark_submit (Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.executor.memory=2g --py-files /dependencies.zip --packages com.datastax.spark:spark-cassandra-connector_2.12:3.5.1 --name docker_spark_task /spark_stream.py. Error code is: 1.; 908)
[2024-12-03T15:25:06.131+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-12-03T15:25:06.146+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T15:25:06.148+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
