<<<<<<< HEAD
[2024-11-30T10:37:26.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T10:37:26.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T09:00:00+00:00 [queued]>
[2024-11-30T10:37:26.104+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T09:00:00+00:00 [queued]>
[2024-11-30T10:37:26.105+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-30T10:37:26.134+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_openweathermap_data> on 2024-11-30 09:00:00+00:00
[2024-11-30T10:37:26.148+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=16053) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T10:37:26.147+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'store_openweathermap_data', 'scheduled__2024-11-30T09:00:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpj2jt0scz']
[2024-11-30T10:37:26.150+0000] {standard_task_runner.py:64} INFO - Started process 16061 to run task
[2024-11-30T10:37:26.151+0000] {standard_task_runner.py:91} INFO - Job 383: Subtask store_openweathermap_data
[2024-11-30T10:37:26.227+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T09:00:00+00:00 [running]> on host 0741a2a1545f
[2024-11-30T10:37:26.368+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='store_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-30T09:00:00+00:00'
[2024-11-30T10:37:26.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T10:37:26.393+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T10:37:26.394+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 146, in store_openweathermap_data
    read_from_kafka_and_store(KAFKA_TOPIC_OPENWEATHER, "openweathermap_data.parquet")
  File "/opt/airflow/dags/kafka_stream.py", line 141, in read_from_kafka_and_store
    logging.error(f"Error reading from Kafka topic {topic_name}: {e}")
                                                                  ^
NameError: name 'e' is not defined
[2024-11-30T10:37:26.413+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=store_openweathermap_data, run_id=scheduled__2024-11-30T09:00:00+00:00, execution_date=20241130T090000, start_date=20241130T103726, end_date=20241130T103726
[2024-11-30T10:37:26.435+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 383 for task store_openweathermap_data (name 'e' is not defined; 16061)
[2024-11-30T10:37:26.487+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-30T10:37:26.513+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T10:37:26.517+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
=======
[2024-11-30T10:02:07.717+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T10:02:07.830+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T09:00:00+00:00 [queued]>
[2024-11-30T10:02:07.853+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T09:00:00+00:00 [queued]>
[2024-11-30T10:02:07.854+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-30T10:02:07.891+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_openweathermap_data> on 2024-11-30 09:00:00+00:00
[2024-11-30T10:02:07.905+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=10377) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T10:02:07.907+0000] {standard_task_runner.py:64} INFO - Started process 10381 to run task
[2024-11-30T10:02:07.905+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'store_openweathermap_data', 'scheduled__2024-11-30T09:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpmfpcsa1s']
[2024-11-30T10:02:07.916+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask store_openweathermap_data
[2024-11-30T10:02:08.013+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-30T09:00:00+00:00 [running]> on host 8885fe629c2f
[2024-11-30T10:02:08.181+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='store_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-30T09:00:00+00:00'
[2024-11-30T10:02:08.183+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T10:02:08.208+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: connecting to broker:9092 [('172.23.0.9', 9092) IPv4]
[2024-11-30T10:02:08.209+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-11-30T10:02:08.211+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: Connection complete.
[2024-11-30T10:02:08.314+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-11-30T10:02:08.315+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-11-30T10:02:08.317+0000] {consumer.py:122} WARNING - group_id is None: disabling auto-commit.
[2024-11-30T10:02:08.318+0000] {subscription_state.py:167} INFO - Updating subscribed topics to: ('openweathermap_raw',)
[2024-11-30T10:02:08.321+0000] {subscription_state.py:253} INFO - Updated partition assignment: [('openweathermap_raw', 0)]
[2024-11-30T10:02:08.324+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: connecting to broker:9092 [('172.23.0.9', 9092) IPv4]
[2024-11-30T10:02:08.325+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: Connection complete.
[2024-11-30T10:02:08.326+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.23.0.9', 9092)]>: Closing connection. 
[2024-11-30T10:02:08.584+0000] {logging_mixin.py:188} INFO - Consumed 100 records from topic openweathermap_raw
[2024-11-30T10:02:08.784+0000] {logging_mixin.py:188} INFO - Data from openweathermap_raw stored in /opt/***/data/parquet_files/openweathermap_data.parquet
[2024-11-30T10:02:08.785+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-30T10:02:08.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T10:02:08.808+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_kafka_dag, task_id=store_openweathermap_data, run_id=scheduled__2024-11-30T09:00:00+00:00, execution_date=20241130T090000, start_date=20241130T100207, end_date=20241130T100208
[2024-11-30T10:02:08.869+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-30T10:02:08.894+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T10:02:08.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
>>>>>>> 604b8b813e1d85ccda3063889c3dd1126b7c5791
